### ISSUE TITLE
panic when creating `awscc_s3_bucket` with `cors_configuration`

### ISSUE THREAD

**Issue by aliscott** [hashicorp/terraform-provider-awscc#226]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the Cloudformation Open Coverage Roadmap.

### Terraform CLI and Terraform AWS Cloud Control Provider Version

```
Terraform v1.0.8
on darwin_amd64
+ provider registry.terraform.io/hashicorp/awscc v0.1.0
```

### Affected Resource(s)

* awscc_s3_bucket

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
terraform {
  required_providers {
    awscc = {
      source  = "hashicorp/awscc"
      version = "~> 0.1"
    }
  }
}
 
provider "awscc" {
  region = "us-east-1"
}

resource "awscc_s3_bucket" "my_bucket" {
  bucket_name = "my-bucket-test-768"
  cors_configuration = {
    cors_rules = [{
      allowed_headers = ["*"]
      allowed_methods = ["GET"]
      allowed_origins = ["*"]
      expose_headers = ["*"]
    }]
  }
}
```

### Panic Output

[crash.log](https://gist.github.com/aliscott/d6ba35c7fcdab3a0f41233efe25db52f)

**Comment by ewbankkit** [comment]
```
panic: not a list, map, or tuple type

goroutine 148 [running]:
github.com/zclconf/go-cty/cty.Value.HasIndex({{{0x3328538, 0xc00140f560}}, {0x2b4ccc0, 0xc001fe3890}}, {{{0x3328458, 0xc000132368}}, {0x2e84a40, 0xc001fe3a40}})
	github.com/zclconf/go-cty@v1.9.1/cty/value_ops.go:953 +0x858
github.com/hashicorp/terraform/internal/plans/objchange.proposedNewNestedType(0xc000d396a0, {{{0x3328538, 0xc00140f560}}, {0x2b4ccc0, 0xc001fe3890}}, {{{0x33284c8, 0xc00140e300}}, {0x2a343a0, 0xc00000e318}})
	github.com/hashicorp/terraform/internal/plans/objchange/objchange.go:333 +0x1347
github.com/hashicorp/terraform/internal/plans/objchange.proposedNewAttributes(0xc000bf90e0, {{{0x3328538, 0xc00140e600}}, {0x0, 0x0}}, {{{0x3328538, 0xc00140e310}}, {0x2b4ccc0, 0xc001f8c480}})
	github.com/hashicorp/terraform/internal/plans/objchange/objchange.go:295 +0x355
github.com/hashicorp/terraform/internal/plans/objchange.proposedNewNestedType(0xc000d39660, {{{0x3328538, 0xc00140e600}}, {0x0, 0x0}}, {{{0x3328538, 0xc00140e310}}, {0x2b4ccc0, 0xc001f8c480}})
	github.com/hashicorp/terraform/internal/plans/objchange/objchange.go:317 +0x255
github.com/hashicorp/terraform/internal/plans/objchange.proposedNewAttributes(0xc000bf84e0, {{{0x3328538, 0xc00140f550}}, {0x2b4ccc0, 0xc001fe37d0}}, {{{0x3328538, 0xc00140e510}}, {0x2b4ccc0, 0xc001f8c4e0}})
	github.com/hashicorp/terraform/internal/plans/objchange/objchange.go:295 +0x355
github.com/hashicorp/terraform/internal/plans/objchange.proposedNew(0xc000bf8570, {{{0x3328538, 0xc00140f550}}, {0x2b4ccc0, 0xc001fe37d0}}, {{{0x3328538, 0xc00140e510}}, {0x2b4ccc0, 0xc001f8c4e0}})
	github.com/hashicorp/terraform/internal/plans/objchange/objchange.go:80 +0x169
github.com/hashicorp/terraform/internal/plans/objchange.ProposedNew(0x3328538, {{{0x3328538, 0xc000d271e0}}, {0x0, 0x0}}, {{{0x3328538, 0xc00140e510}}, {0x2b4ccc0, 0xc001f8c4e0}})
	github.com/hashicorp/terraform/internal/plans/objchange/objchange.go:42 +0x13a
github.com/hashicorp/terraform/internal/terraform.(*NodeAbstractResourceInstance).plan(0xc0017fa000, {0x3390960, 0xc000b18e00}, 0x0, 0x0, 0x0, {0x0, 0x0, 0x0})
	github.com/hashicorp/terraform/internal/terraform/node_resource_abstract_instance.go:732 +0xc46
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).managedResourceExecute(0xc001cbc0f0, {0x3390960, 0xc000b18e00})
	github.com/hashicorp/terraform/internal/terraform/node_resource_plan_instance.go:196 +0x7a5
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).Execute(0x0, {0x3390960, 0xc000b18e00}, 0x0)
	github.com/hashicorp/terraform/internal/terraform/node_resource_plan_instance.go:54 +0x90
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc000e41860, {0x3390960, 0xc000b18e00}, {0x2d6034b0, 0xc001cbc0f0})
	github.com/hashicorp/terraform/internal/terraform/graph_walk_context.go:129 +0xc7
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x2e751e0, 0xc001cbc0f0})
	github.com/hashicorp/terraform/internal/terraform/graph.go:59 +0x2c3
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc0006a8d80, {0x2e751e0, 0xc001cbc0f0}, 0xc00104ccc0)
	github.com/hashicorp/terraform/internal/dag/walk.go:381 +0x2f1
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
	github.com/hashicorp/terraform/internal/dag/walk.go:304 +0xf85
 awscc  11:23:43
```
