### ISSUE TITLE
awscc_backup_framework panic on subsequent state refresh

### ISSUE THREAD

**Issue by papile** [hashicorp/terraform-provider-awscc#382]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Terraform CLI and Terraform AWS Cloud Control Provider Version

terraform version: 1.1.5 Linux
awscc provider version: 0.11

### Affected Resource(s)

* awscc_backup_framework

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "awscc_backup_framework" "backup-framework"{
  framework_name = "ProdBackupFramework"
  framework_controls = [
    {
      control_name = "BACKUP_RECOVERY_POINT_MINIMUM_RETENTION_CHECK"
      control_input_parameters = [
        {
          parameter_name = "requiredRetentionDays"
          parameter_value = "35"
        }
      ]
      control_scope = {}
    },
    {
      control_name = "BACKUP_PLAN_MIN_FREQUENCY_AND_MIN_RETENTION_CHECK"
      control_scope = {
        tags = [
            {
              key = "PersistentDataClass",
              value = "protected"
            }
          ]
      }
      control_input_parameters = [
        {
          parameter_name = "requiredRetentionDays"
          parameter_value = "35"
        },
        {
          parameter_name = "requiredFrequencyUnit",
          parameter_value = "hours"
        },
        {
          parameter_name = "requiredFrequencyValue",
          parameter_value = "24"
        }
      ]
    },
    {
      control_name  = "BACKUP_RESOURCES_PROTECTED_BY_BACKUP_PLAN"
      control_input_parameters = []
      control_scope = {
        compliance_resource_types = [
          "DynamoDB",
          "EBS",
          "RDS",
          "EFS",
          "Aurora",
          "EC2",
          "FSx"
        ]
      }
    }
  ]
}
```

### Debug Output
https://gist.github.com/papile/b1c56243dd4168801c99babdf7d0dc8f

### Panic Output

```sh
Stack trace from the terraform-provider-awscc plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x5ea0ed]

goroutine 89 [running]:
github.com/hashicorp/terraform-plugin-framework/types.SetType.Validate(0x190cc58, 0xc0002d91a0, 0x190a7b8, 0xc000a6a900, 0x0, 0x0, 0x0, 0x0, 0xc000f60168, 0x1677a00, ...)
        github.com/hashicorp/terraform-plugin-framework@v0.5.1-0.20220105213120-5f18d804a22b/types/set.go:118 +0x6d  
github.com/hashicorp/terraform-plugin-framework/tfsdk.State.getAttributeValue(0x1912c08, 0xc0009769c0, 0x15ce4c0, 0xc00096d200, 0xc0003e17d0, 0x0, 0x1, 0x0, 0x0, 0x176c240, ...)
        github.com/hashicorp/terraform-plugin-framework@v0.5.1-0.20220105213120-5f18d804a22b/tfsdk/state.go:95 +0x514
github.com/hashicorp/terraform-plugin-framework/tfsdk.Attribute.modifyPlan(0x0, 0x0, 0x1915808, 0xc00101ff98, 0x1721732, 0x31, 0x0, 0x0, 0x100, 0x0, ...)
        github.com/hashicorp/terraform-plugin-framework@v0.5.1-0.20220105213120-5f18d804a22b/tfsdk/attribute.go:487 +0x1d7
github.com/hashicorp/terraform-plugin-framework/tfsdk.Attribute.modifyPlan(0x0, 0x0, 0x1915808, 0xc00101ffc8, 0x175ae1b, 0x79, 0x0, 0x0, 0x1, 0x0, ...)
        github.com/hashicorp/terraform-plugin-framework@v0.5.1-0.20220105213120-5f18d804a22b/tfsdk/attribute.go:604 +0x2205
github.com/hashicorp/terraform-plugin-framework/tfsdk.Schema.modifyPlan(0xc0003e17d0, 0x0, 0x1, 0x0, 0x0, 0x176c240, 0xba, 0x0, 0x0, 0x190a7b8, ...)
        github.com/hashicorp/terraform-plugin-framework@v0.5.1-0.20220105213120-5f18d804a22b/tfsdk/schema.go:321 +0x248
github.com/hashicorp/terraform-plugin-framework/tfsdk.(*server).planResourceChange(0xc000518540, 0x190a7b8, 0xc000a6a900, 0xc0001bea00, 0xc00059d9f0)
        github.com/hashicorp/terraform-plugin-framework@v0.5.1-0.20220105213120-5f18d804a22b/tfsdk/serve.go:821 +0x1968
github.com/hashicorp/terraform-plugin-framework/tfsdk.(*server).PlanResourceChange(0xc000518540, 0x190a7b8, 0xc000a6a8c0, 0xc0001bea00, 0x16deb23, 0x12, 0x0)
        github.com/hashicorp/terraform-plugin-framework@v0.5.1-0.20220105213120-5f18d804a22b/tfsdk/serve.go:642 +0xc8
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).PlanResourceChange(0xc00051a200, 0x190a860, 0xc000a6a8c0, 0xc0003a01c0, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov6/tf6server/server.go:579 +0x465
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_PlanResourceChange_Handler(0x1692f40, 0xc00051a200, 0x190a860, 0xc00074e4b0, 0xc000748540, 0x0, 0x190a860, 0xc00074e4b0, 0xc0008ae400, 0xab3)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:363 +0x214 
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002fce00, 0x1916098, 0xc000103080, 0xc000aa2200, 0xc000518660, 0x1f3b5e8, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0002fce00, 0x1916098, 0xc000103080, 0xc000aa2200, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0001221f0, 0xc0002fce00, 0x1916098, 0xc000103080, 0xc000aa2200)
        google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`

Panic goes away when resource is removed from the TF file, and then it gets deleted. But as long as it exists it gives panics on subsequent state/plan generation. Original apply makes the resource successfully.

**Comment by ewbankkit** [comment]
https://github.com/hashicorp/terraform-plugin-framework/blob/5f18d804a22bb86da3cfadff07a58e419b9b0f73/types/set.go#L118-L126

**Comment by ewbankkit** [comment]
Attempting to plan the specified configuration now:

```console
% terraform plan
...
╷
│ Error: Incorrect attribute value type
│ 
│   on main.tf line 7, in resource "awscc_backup_framework" "backup-framework":
│    7:   framework_controls = [
│    8:     {
│    9:       control_name = "BACKUP_RECOVERY_POINT_MINIMUM_RETENTION_CHECK"
│   10:       control_input_parameters = [
│   11:         {
│   12:           parameter_name  = "requiredRetentionDays"
│   13:           parameter_value = "35"
│   14:         }
│   15:       ]
│   16:       control_scope = {}
│   17:     },
│   18:     {
│   19:       control_name = "BACKUP_PLAN_MIN_FREQUENCY_AND_MIN_RETENTION_CHECK"
│   20:       control_scope = {
│   21:         tags = [
│   22:           {
│   23:             key   = "PersistentDataClass",
│   24:             value = "protected"
│   25:           }
│   26:         ]
│   27:       }
│   28:       control_input_parameters = [
│   29:         {
│   30:           parameter_name  = "requiredRetentionDays"
│   31:           parameter_value = "35"
│   32:         },
│   33:         {
│   34:           parameter_name  = "requiredFrequencyUnit",
│   35:           parameter_value = "hours"
│   36:         },
│   37:         {
│   38:           parameter_name  = "requiredFrequencyValue",
│   39:           parameter_value = "24"
│   40:         }
│   41:       ]
│   42:     },
│   43:     {
│   44:       control_name             = "BACKUP_RESOURCES_PROTECTED_BY_BACKUP_PLAN"
│   45:       control_input_parameters = []
│   46:       control_scope = {
│   47:         compliance_resource_types = [
│   48:           "DynamoDB",
│   49:           "EBS",
│   50:           "RDS",
│   51:           "EFS",
│   52:           "Aurora",
│   53:           "EC2",
│   54:           "FSx"
│   55:         ]
│   56:       }
│   57:     }
│   58:   ]
│ 
│ Inappropriate value for attribute "framework_controls": element types must all match for conversion to set.
╵
```
