### ISSUE TITLE
Bug in awscc: networkmanager_core_network updates (using cdktf )

### ISSUE THREAD

**Issue by manojkaushal** [hashicorp/terraform-provider-awscc#699]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Terraform CLI and Terraform AWS Cloud Control Provider Version
`Terraform v1.3.3`
`cdktf v0.13.1`

### Affected Resource(s)

* awscc_networkmanager_core_network

### Terraform Configuration Files
I am using awscc provider to create core network in aws. 

snippet of code:
```
from imports.awscc.networkmanager_core_network import NetworkmanagerCoreNetwork as Nm_Core_Network, \
    NetworkmanagerCoreNetworkTags as Nm_Core_Network_Tags

        _core_network = Nm_Core_Network(self, core_network_name,
                                        global_network_id=global_network_id,
                                        description=core_network_description,
                                        policy_document=Fn.jsonencode(create_core_network_policy_document()),
                                       
```
the stack runs fine and creates the core network. After the stack execution, tfstate file stores core network owner account as Null(this is the bug):
```
 "owner_account": null,
```

The next run of "cdktf deploy" without any changes in the stack, tries update "owner_account" parameter 
```
~ resource "awscc_networkmanager_core_network" "name of the core network stack id" {
                     id                = "core-network-id"
                    + owner_account     = (known after apply)
```
but since there is no actual change and cdktf is unable to parse the "owner_account" by calling cloud_control API, "cdktf deploy" is running for hours before timeout.

```
Still modifying... [id=core-network-id, 1h10m elapsed]
```

If you make direct call to cloud-control API, it does return the "owner_account" parameter:
```
% aws cloudcontrol list-resources --type-name AWS::NetworkManager::CoreNetwork
{
    "ResourceDescriptions": [
        {
            "Identifier": "core-network-id",
            "Properties": "{\"CoreNetworkId\":\"core-network-id\",\"GlobalNetworkId\":\"global-network-id\",\"Description\":\"Cdescription\",\"State\":\"AVAILABLE\",\"OwnerAccount\":\"<owner-account>\",\"Tags\":[],\"CoreNetworkArn\":\"arn:aws:networkmanager::<arn>\"}"
        },
```

The only workaround is to ignore_changes using lifecyle meta-argument:
```
lifecycle=TerraformResourceLifecycle(
                                            ignore_changes="all"
                                        )
```

### Debug Output
terraformoutput for:
```
       TerraformOutput(self, "core_network_owner",
                        value=_core_network.owner_account)
```
fails:
```
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at nJe (/usr/local/Cellar/cdktf/0.13.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:464:9638)
    at kd (/usr/local/Cellar/cdktf/0.13.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:193:19924)
    at ws (/usr/local/Cellar/cdktf/0.13.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:197:7164)
    at Cv (/usr/local/Cellar/cdktf/0.13.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:197:983)
    at $9 (/usr/local/Cellar/cdktf/0.13.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:197:911)
    at Kf (/usr/local/Cellar/cdktf/0.13.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:197:766)
    at cg (/usr/local/Cellar/cdktf/0.13.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:195:12546)
    at /usr/local/Cellar/cdktf/0.13.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:193:4411
    at Ga.unstable_runWithPriority (/usr/local/Cellar/cdktf/0.13.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:189:7574)

  ERROR  Cannot convert undefined or null to object

 -     at Function.entries (<anonymous>)
 - nJe (/usr/local/Cellar/cdktf/0.13.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:464:9638)
 - kd (/usr/local/Cellar/cdktf/0.13.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:193:19924)
 - ws (/usr/local/Cellar/cdktf/0.13.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:197:7164)
 - Cv (/usr/local/Cellar/cdktf/0.13.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:197:983)
 - $9 (/usr/local/Cellar/cdktf/0.13.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:197:911)
 - Kf (/usr/local/Cellar/cdktf/0.13.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:197:766)
 - cg (/usr/local/Cellar/cdktf/0.13.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:195:12546)
 -  (/usr/local/Cellar/cdktf/0.13.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:193:4411)
 - Ga.unstable_runWithPriority (/usr/local/Cellar/cdktf/0.13.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:189:7574)
```

```
cdktf --version
0.13.1

  "terraformProviders": [
    {
      "name": "awscc",
      "source": "hashicorp/awscc",
      "version": "~> 0.32.0"
    }
```

### References

* #0000

**Comment by kadrach** [comment]
Are you still running into this issue with newer versions of the provider? I have tried to reproduce it with the following minimal example, but it seems to work (the owner account is retrieved and stored in the state file).

```hcl
terraform {
  required_providers {
    awscc = {
      source = "hashicorp/awscc"
    }
  }
}

provider "awscc" {}

resource "awscc_networkmanager_global_network" "this" {}

resource "awscc_networkmanager_core_network" "this" {
  global_network_id = awscc_networkmanager_global_network.this.id
}
```
